scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "statsd_exporter"
    static_configs:
      - targets: ["localhost:9102"]

remote_write:
  - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: "23413243"
      password: 394534pjiprtoiwjeprdkpgodjpgoi
